# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-ImageSpool
version:      0.01
version_from: lib/WWW/ImageSpool.pm
installdirs:  site
requires:
    Getopt::Long:                  0
    Image::Size:                   0
    LWP:                           0
    WWW::Google::Images:           0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
